"""
SOAR export helpers.

Turn a list of malicious IPs into defensive action artifacts:
    - bash firewall rules (iptables + ipset)
    - pfSense CLI commands
    - CSV for spreadsheet / SIEM ingestion
"""

import csv
import io
from typing import Any, Dict, Iterable, List


def _norm_ips(ips: Iterable[str]) -> List[str]:
    """Strip, dedupe, and drop empties while preserving order."""
    seen = set()
    out = []
    for ip in ips or []:
        s = str(ip).strip()
        if not s or s in seen:
            continue
        seen.add(s)
        out.append(s)
    return out


def generate_firewall_rules(ips: Iterable[str], comment: str = "PRAMAAN-BLOCK") -> str:
    """Return a bash script that blocks each IP via iptables.

    Uses ipset for scalable matching, and iptables for the DROP rule.
    """
    clean = _norm_ips(ips)
    lines = [
        "#!/usr/bin/env bash",
        "set -euo pipefail",
        "",
        "# Generated by PRAMAAN SOAR export",
        "# Usage: sudo bash block_ips.sh",
        "",
        "SET_NAME=\"pramaan_block\"",
        "",
        "ipset create \"$SET_NAME\" hash:ip -exist",
        "",
    ]
    for ip in clean:
        lines.append(f'ipset add "$SET_NAME" {ip} -exist')
    lines += [
        "",
        f'iptables -C INPUT -m set --match-set "$SET_NAME" src -j DROP 2>/dev/null || \\',
        f'    iptables -I INPUT -m set --match-set "$SET_NAME" src -j DROP -m comment --comment "{comment}"',
        "",
        'echo "PRAMAAN: rules applied for $SET_NAME set"',
        "",
    ]
    return "\n".join(lines)


def generate_pfsense_rules(ips: Iterable[str], alias_name: str = "PRAMAAN_BLOCK") -> str:
    """Return pfSense CLI commands to block each IP.

    pfctl expects a table alias. Provide add commands and a load step.
    """
    clean = _norm_ips(ips)
    lines = [
        "# Generated by PRAMAAN SOAR export",
        "# Run in pfSense Diagnostics > Command Prompt, or via SSH as root.",
        "",
        f"# Create alias/table if missing:",
        f"#   pfctl -t {alias_name} -T add <ip>",
        "",
    ]
    for ip in clean:
        lines.append(f"pfctl -t {alias_name} -T add {ip}")
    lines += [
        "",
        "# Reload filter rules to apply the table changes:",
        "pfctl -f /etc/filter.rules",
        "",
    ]
    return "\n".join(lines)


def generate_csv(records: List[Dict[str, Any]]) -> str:
    """Return CSV text with columns: IP, ASN, Country, Risk Score.

    Each record should have at least:
        source_ip or ip
        asn
        country
        risk_score
    """
    buf = io.StringIO()
    writer = csv.writer(buf)
    writer.writerow(["IP", "ASN", "Country", "Risk Score"])
    for r in records or []:
        writer.writerow([
            r.get("source_ip", r.get("ip", "")),
            r.get("asn", ""),
            r.get("country", ""),
            r.get("risk_score", ""),
        ])
    return buf.getvalue()